<a href="https://colab.research.google.com/github/arsumjavaid-cs/IITGN_PGD_AIML_Assignments/blob/main/Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas **Assignment**

Submitted by: Arsum Javaid (26271006)

In [ ]:

import pandas as pd

s = pd.Series([1250, 980, 1540, 760, 2100, 1320], index=["C101","C102","C103","C104","C105","C106"])

# Question 1: Write code to select `"C103"` and `"C106"` in this exact order (return a Series).

In [ ]:
s[['C103', 'C106']]

C103    1540
C106    1320
dtype: int64

Question 2

In [ ]:
import pandas as pd

s2 = pd.Series([72, 88, 91, 67, 85, 90, 79], index=["S1","S2","S3","S4","S5","S6","S7"])
# Write code to select the 2nd, 4th, and 6th elements using positional indexing (return a Series).

In [ ]:
s2[1:6:2]

S2    88
S4    67
S6    90
dtype: int64

Question 3

In [ ]:
import pandas as pd

s = pd.Series([31.2, 32.0, 33.5, 34.1, 32.8, 31.9, 30.7], index=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])

# Write code to slice `"Tue"` through `"Sat"` (inclusive) using label-based slicing.

In [ ]:
s['Tue':'Sat']

Tue    32.0
Wed    33.5
Thu    34.1
Fri    32.8
Sat    31.9
dtype: float64

Question 4

In [ ]:
import pandas as pd

s = pd.Series([14, 9, 11, 7, 15], index=["P_A","P_B","P_C","P_D","P_E"])
# Write code to update only "P_D" to 10.

In [ ]:
s['P_D'] = 10
s

P_A    14
P_B     9
P_C    11
P_D    10
P_E    15
dtype: int64

Question 5

In [ ]:
import pandas as pd

s = pd.Series([4.2, 3.8, 4.6, 2.9, 4.1], index=["r1","r2","r3","r4","r5"])

# Write code to create a new Series with only `["r5","r2","r3"]` in this exact order.

In [ ]:
s2 = s[["r5", "r2", "r3"]]
s2

r5    4.1
r2    3.8
r3    4.6
dtype: float64

Question 6

In [ ]:
import pandas as pd

s = pd.Series([18000, 32000, 25000, 41000, 15000, 28000], index=["U1","U2","U3","U4","U5","U6"])
# Write code to filter and return only values strictly greater than 25000.

In [ ]:
s[s>25000]

U2    32000
U4    41000
U6    28000
dtype: int64

Question 7

In [ ]:
import pandas as pd

s = pd.Series([22, 35, 29, 41, 27, 33, 19], index=list("ABCDEFG"))

# Write code to keep entries where `(s >= 25) & (s <= 35)` using `&`

In [ ]:
s[(s>=25) & (s<=35)]

B    35
C    29
E    27
F    33
dtype: int64

Question 8

In [ ]:
import pandas as pd

s = pd.Series([0, 5, 12, 0, 31, 8, 0, 18], index=[f"L{i}" for i in range(1,9)])
# Write code to keep entries where (s == 0) | (s >= 15) using |.

In [ ]:
s[(s==0) | (s>=15)]

L1     0
L4     0
L5    31
L7     0
L8    18
dtype: int64

Question 9

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([1200, np.nan, 450, 2100, np.nan, 980, 1550], index=["a","b","c","d","e","f","g"])

#Write code to keep entries that are `(s.notna()) & (s > 900)` using `&`

In [ ]:
s[(s.notna()) & (s>900)]

a    1200.0
d    2100.0
f     980.0
g    1550.0
dtype: float64

Question 10

In [ ]:
import pandas as pd

s = pd.Series([3, 0, 5, 2, 0, 1, 4, 2], index=["K1","K2","K3","K4","K5","K6","K7","K8"])
# Write code to create a new Series where values become -1 wherever (s == 0) | (s == 1).

In [ ]:
def change_values(number):
  if (number == 0) | (number == 1):
    number = -1
  return number

In [ ]:
s2 = s.apply(change_values)
s2

K1    3
K2   -1
K3    5
K4    2
K5   -1
K6   -1
K7    4
K8    2
dtype: int64

Question 11

In [ ]:
import pandas as pd

s = pd.Series([180, 240, 95, 310, 130, 260, 150, 400], index=["req1","req2","req3","req4","req5","req6","req7","req8"])

# Write code to compute the mean of values where `(s >= 120) & (s <= 260)`.

In [ ]:
s[(s>=120) & (s<=260)].mean()

np.float64(192.0)

Question 12

In [ ]:
import pandas as pd

s = pd.Series([1.2, 3.5, 0.8, 10.1, 6.6], index=["t1","t2","t3","t4","t5"])
# Using apply, create a new Series converting miles to km (x * 1.60934) and rounding to 2 decimals.

In [ ]:
s2 = (s*1.60934).round(2)
s2

t1     1.93
t2     5.63
t3     1.29
t4    16.25
t5    10.62
dtype: float64

Question 13

In [ ]:
import pandas as pd

s = pd.Series([0.12, 0.66, 0.48, 0.91, 0.35, 0.70, 0.05], index=["p1","p2","p3","p4","p5","p6","p7"])

#Using `apply`, map values to `"LOW"` if `< 0.4`, `"MID"` if `0.4 to 0.7` inclusive, otherwise `"HIGH"`

In [ ]:
def grade(num):
  if num < 0.4:
    return "LOW"
  elif num < 0.7:
    return "MID"
  else:
    return "HIGH"

In [ ]:
s.apply(grade)

p1     LOW
p2     MID
p3     MID
p4    HIGH
p5     LOW
p6    HIGH
p7     LOW
dtype: object

Question 14

In [ ]:
import pandas as pd

s = pd.Series(["₹12,500", "₹999", "₹2,050", "₹18,000", "₹7,499"], index=["i1","i2","i3","i4","i5"])
# Using apply, convert this Series into integers by removing ₹ and commas.

In [ ]:
def clean_value(val):
  cleaned = val.replace("₹", "").replace(",","")
  return cleaned

In [ ]:
s.apply(clean_value)

i1    12500
i2      999
i3     2050
i4    18000
i5     7499
dtype: object

Question 15

In [ ]:
import pandas as pd

s = pd.Series([" ankit ", "Riya", " MOHAN", "neha ", " ViKRaM "], index=["n1","n2","n3","n4","n5"])

# Using `apply`, strip spaces and convert each string to title case.

In [ ]:
def change_val(val):
  new_val = val.strip().title()
  return new_val

In [ ]:
s.apply(change_val)

n1     Ankit
n2      Riya
n3     Mohan
n4      Neha
n5    Vikram
dtype: object

Question 16

In [ ]:
import pandas as pd

s = pd.Series(["delhi", "mumbai", "pune", "delhi", "jaipur", "pune", "delhi"], index=["c1","c2","c3","c4","c5","c6","c7"])
# Write code to keep only entries where (s == "delhi") | (s == "pune") using |.

In [ ]:
s[(s=="delhi") | (s== "pune")]

c1    delhi
c3     pune
c4    delhi
c6     pune
c7    delhi
dtype: object

Question 17

In [ ]:
import pandas as pd

s = pd.Series([500, -120, 0, 240, -5, 910, 30], index=["A1","A2","A3","A4","A5","A6","A7"])

# Write code to keep entries where `(s <= 0) | (s >= 500)` using `|`.

In [ ]:
s[(s<=0) | (s>=500)]

A1    500
A2   -120
A3      0
A5     -5
A6    910
dtype: int64

Question 18

In [ ]:
import pandas as pd

s = pd.Series(["AX-120", "BX-9", "AX-450", "CX-12", "AX-7", "BX-200"], index=["s1","s2","s3","s4","s5","s6"])
# Write code to filter entries where (s.str.startswith("AX")) & (s.str.len() > 4) using &.

In [ ]:
s[(s.str.startswith("AX")) & (s.str.len() > 4)]

s1    AX-120
s3    AX-450
dtype: object

Question 19

In [ ]:
import pandas as pd

qty = pd.Series([2, 5, 1, 8, 3, 10, 6], index=["o1","o2","o3","o4","o5","o6","o7"])
price = pd.Series([120, 80, 200, 50, 150, 40, 90], index=["o1","o2","o3","o4","o5","o6","o7"])

# Create `revenue = qty * price` (Series alignment). Then filter `revenue` where `(revenue >= 300) & (revenue <= 700)`.

In [ ]:
revenue = qty*price
lolo = (revenue>=300) & (revenue<=700)
revenue[lolo]

o2    400
o4    400
o5    450
o6    400
o7    540
dtype: int64

Question 20

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([0.10, 0.55, np.nan, 0.92, 0.30, 0.75, np.nan, 0.05], index=["u1","u2","u3","u4","u5","u6","u7","u8"])
# Do both:

# Filter entries where (s.notna()) & (s > 0.2) using &.
# Using apply, create a new Series where missing values become -1, else keep the original value.

In [ ]:
#Code to filter Entries
(s.notna()) & (s>0.2)

u1    False
u2     True
u3    False
u4     True
u5     True
u6     True
u7    False
u8    False
dtype: bool

In [ ]:
#Using Apply Function
def change_values(val):
  if np.isnan(val):
    return -1
  else:
    return val

In [ ]:
s.apply(change_values)

u1    0.10
u2    0.55
u3   -1.00
u4    0.92
u5    0.30
u6    0.75
u7   -1.00
u8    0.05
dtype: float64